
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const SET_USERNAME_AND_EMAIL = 'SET_USERNAME_AND_EMAIL';
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';
export const SET_PROFILE_IMAGE = 'SET_PROFILE_IMAGE';
export const SET_THEME_IMAGE = 'SET_THEME_IMAGE';
export const SET_THEME_INDEX = 'SET_THEME_INDEX';
export const SET_BIO = 'SET_BIO';
export const SET_PASSWORD = 'SET_PASSWORD';
export const RESET_AUTH_PARAMETERS = 'RESET_AUTH_PARAMETERS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
