
export const SET_RECEIVED_REQUESTS = 'SET_RECEIVED_REQUESTS';
export const SET_SENT_REQUESTS = 'SET_SENT_REQUESTS';
export const REQUEST_SUCCESS = 'REQUEST_SUCCESS';
export const REQUEST_FAIL = 'REQUEST_FAIL';
